#!/usr/bin/env python3
"""Copy WSL NuttX images to the Windows contest tree.

With no arguments this refreshes the current v3.2 NSH files used by the flash
script. ``--variant v1.x`` writes only to the historical archive; v3 variants
stay under the current ``firmware/v3`` entry point.
"""
import argparse
from pathlib import Path
import shutil

src_dir = Path("/home/flash/vela-p4/nuttx")
repo_root = Path(
    "/mnt/c/Users/flash/Desktop/openvela-contest/"
    "contest2026_359_dengfengzaojidecuipidaxuesheng"
)
parser = argparse.ArgumentParser()
parser.add_argument("--variant", choices=("v1.x", "v3.2", "v3.2-usb"))
args = parser.parse_args()

if args.variant == "v1.x":
    dst = repo_root / "firmware/历史测试固件/esp32p4-nsh-v1.x"
elif args.variant == "v3.2-usb":
    dst = repo_root / "firmware/v3/esp32p4-nsh-v3.2-usb"
else:
    dst = repo_root / "firmware/v3/esp32p4-nsh-v3.2"
dst.mkdir(parents=True, exist_ok=True)
copied = []
# The final `make` step replaces the temporary objcopy dump with the
# Simple-Boot image generated by the tree's pinned esptool (currently 4.8.1).
# Copy that image verbatim.  Re-running elf2image with newer Windows esptool
# releases can collapse the two entry-address sections and produces an image
# which stalls in the ESP32-P4 ROM/bootloader analog initialization.
if args.variant is None:
    outputs = {
        "nuttx.bin": "nuttx.bin",
        "nuttx.hex": "nuttx.hex",
        "nuttx": "nuttx",
        "nuttx.map": "nuttx.map",
    }
else:
    outputs = {
        "nuttx.bin": f"esp32p4-nsh-{args.variant}.bin",
        "nuttx.hex": f"nuttx-{args.variant}.hex",
        "nuttx": f"nuttx-{args.variant}.elf",
        "nuttx.map": f"nuttx-{args.variant}.map",
        ".config": f"nuttx-{args.variant}.config",
    }

for source_name, output_name in outputs.items():
    s = src_dir / source_name
    if s.exists() and s.is_file():
        shutil.copy2(s, dst / output_name)
        copied.append(f"{output_name} {s.stat().st_size}")
print("DST", dst)
print("COPIED", copied)
image_name = "nuttx.bin" if args.variant is None else f"esp32p4-nsh-{args.variant}.bin"
if not (dst / image_name).exists():
    raise SystemExit("Simple-Boot nuttx.bin missing; build not finished")
